#!/usr/bin/env bash
status=$(cat /sys/class/power_supply/BAT*/status)

if [[ $status == "Discharging" ]]; then
	echo ""
elif [[ $status == "Charging" ]]; then
	echo ""
fi

if [[ $1 == 'new' ]]; then

	udevadm monitor --udev --subsystem-match=power_supply --property | while read -r line; do
		echo $line
		# | grep -A 12 "AC0 (power_supply)"'
	done
fi
